In [51]:
# import pandas as pd
# from sklearn.preprocessing import LabelEncoder
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
categori_col = df.select_dtypes(include=["object"]).columns
print(categori_col)

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [8]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [9]:
categori_col

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [17]:
# mode function is return the which come more time use this value in think the value is tied come the 2 value to gether in the mode 
# Example: if values are ['S','C','S','Q','S'], then df["Embarked"].mode() returns ['S'].
# If two values are tied, you get both (e.g. ['C','S']).
df["Embarked"].fillna(df["Embarked"].mode()[0],inplace=True)
# handle the Embarked column

In [15]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [18]:
df["Embarked"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Embarked
Non-Null Count  Dtype
--------------  -----
891 non-null    object
dtypes: object(1)
memory usage: 7.1+ KB

In [21]:
df.loc[61,["Name"]]
df.loc[61,["Embarked"]]

Embarked    S
Name: 61, dtype: object

In [25]:
df["Cabin"].fillna("Unknown", inplace=True)
# handel the cabin data

In [23]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Unknown,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,Unknown,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,Unknown,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Unknown,Q

In [26]:
# handel the gender male and female 
le = LabelEncoder()
df["Sex"] = le.fit_transform(df["Sex"]) # male=1, female=0

In [27]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,Unknown,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",1,27.0,0,0,211536,13.0000,Unknown,S
887,888,1,1,"Graham, Miss. Margaret Edith",0,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",0,NaN,1,2,W./C. 6607,23.4500,Unknown,S
889,890,1,1,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",1,32.0,0,0,370376,7.7500,Unknown,Q

In [28]:
# One-Hot Encoding (for nominal categories, no order)
# Creates separate columns for each category value:
df = pd.get_dummies(df, columns=["Embarked"], drop_first=True)

In [29]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,Unknown,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,False,False
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,False,True
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,Unknown,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",1,27.0,0,0,211536,13.0000,Unknown,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",0,19.0,0,0,112053,30.0000,B42,False,True
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",0,NaN,1,2,W./C. 6607,23.4500,Unknown,False,True
889,890,1,1,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,C148,False,False
890,891,0,3,"Dooley, Mr. Patrick",1,32.0,0,0,370376,7.7500,Unknown,True,False

In [30]:
df["Title"] = df["Name"].str.extract(' ([A-Za-z]+)\.', expand=False)
df["Title"] = df["Title"].replace(['Mlle', 'Ms'], 'Miss')
df["Title"] = df["Title"].replace(['Mme'], 'Mrs')

# Encode Title
df = pd.get_dummies(df, columns=["Title"], drop_first=True)

In [31]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,Title_Dr,Title_Jonkheer,Title_Lady,Title_Major,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rev,Title_Sir
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,...,False,False,False,False,False,False,True,False,False,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,...,False,False,False,False,False,False,False,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,...,False,False,False,False,False,True,False,False,False,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,...,False,False,False,False,False,False,False,True,False,False
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",1,27.0,0,0,211536,13.0000,...,False,False,False,False,False,False,False,False,True,False
887,888,1,1,"Graham, Miss. Margaret Edith",0,19.0,0,0,112053,30.0000,...,False,False,False,False,False,True,False,False,False,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",0,NaN,1,2,W./C. 6607,23.4500,...,False,False,False,False,False,True,False,False,False,False
889,890,1,1,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,...,False,False,False,False,False,False,True,False,False,False
890,891,0,3,"Dooley, Mr. Patrick",1,32.0,0,0,370376,7.7500,...,False,False,False,False,False,False,True,False,False,False

In [32]:
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0
2                             Heikkinen, Miss. Laina    0  26.0      0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0
4                           Allen, Mr. William Henry    1  35.0      0      0

             Ticket     Fare  ... Title_Dr  Title_Jonkheer  Title_Lady  \
0         A/5 21171   7.2500  ...    False           False       False
1          PC 17599  71.2833  ...    False           False       False
2  STON/O2. 3101282   7.9250  ...    False           False       False
3            113803  53.1000  ...    False           False       False
4            373450   8.0500  ...    False           False       False

   Title_Major  Title_Master  Title_Miss  Title_Mr  Title_Mrs  Title_Rev  \
0        False         False       False      True      False      False
1        False         False       False     False       True      False
2        False         False        True     False      False      False
3        False         False       False     False       True      False
4        False         False       False      True      False      False

   Title_Sir
0      False
1      False
2      False
3      False
4      False

[5 rows x 26 columns]

In [33]:
df.drop(columns=["Name", "Ticket", "Cabin"], inplace=True)

In [34]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S,...,Title_Dr,Title_Jonkheer,Title_Lady,Title_Major,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rev,Title_Sir
0,1,0,3,1,22.0,1,0,7.2500,False,True,...,False,False,False,False,False,False,True,False,False,False
1,2,1,1,0,38.0,1,0,71.2833,False,False,...,False,False,False,False,False,False,False,True,False,False
2,3,1,3,0,26.0,0,0,7.9250,False,True,...,False,False,False,False,False,True,False,False,False,False
3,4,1,1,0,35.0,1,0,53.1000,False,True,...,False,False,False,False,False,False,False,True,False,False
4,5,0,3,1,35.0,0,0,8.0500,False,True,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,1,27.0,0,0,13.0000,False,True,...,False,False,False,False,False,False,False,False,True,False
887,888,1,1,0,19.0,0,0,30.0000,False,True,...,False,False,False,False,False,True,False,False,False,False
888,889,0,3,0,NaN,1,2,23.4500,False,True,...,False,False,False,False,False,True,False,False,False,False
889,890,1,1,1,26.0,0,0,30.0000,False,False,...,False,False,False,False,False,False,True,False,False,False
890,891,0,3,1,32.0,0,0,7.7500,True,False,...,False,False,False,False,False,False,True,False,False,False

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PassengerId     891 non-null    int64
 1   Survived        891 non-null    int64
 2   Pclass          891 non-null    int64
 3   Sex             891 non-null    int64
 4   Age             714 non-null    float64
 5   SibSp           891 non-null    int64
 6   Parch           891 non-null    int64
 7   Fare            891 non-null    float64
 8   Embarked_Q      891 non-null    bool
 9   Embarked_S      891 non-null    bool
 10  Title_Col       891 non-null    bool
 11  Title_Countess  891 non-null    bool
 12  Title_Don       891 non-null    bool
 13  Title_Dr        891 non-null    bool
 14  Title_Jonkheer  891 non-null    bool
 15  Title_Lady      891 non-null    bool
 16  Title_Major     891 non-null    bool
 17  Title_Master    891 non-null    bool
 18  Title_Miss      891 non-null    bool
 19  Title_Mr        891 non-null    bool
 20  Title_Mrs       891 non-null    bool
 21  Title_Rev       891 non-null    bool
 22  Title_Sir       891 non-null    bool
dtypes: bool(15), float64(2), int64(6)
memory usage: 68.9 KB

In [36]:
# handel the missing age 
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Fare"].fillna(df["Fare"].median(), inplace=True)

C:\Users\keyur\AppData\Local\Temp\ipykernel_14560\568685072.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(), inplace=True)
C:\Users\keyur\AppData\Local\Temp\ipykernel_14560\568685072.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Fare"].fillna(df["Fare"].median(), inplace=True)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PassengerId     891 non-null    int64
 1   Survived        891 non-null    int64
 2   Pclass          891 non-null    int64
 3   Sex             891 non-null    int64
 4   Age             891 non-null    float64
 5   SibSp           891 non-null    int64
 6   Parch           891 non-null    int64
 7   Fare            891 non-null    float64
 8   Embarked_Q      891 non-null    bool
 9   Embarked_S      891 non-null    bool
 10  Title_Col       891 non-null    bool
 11  Title_Countess  891 non-null    bool
 12  Title_Don       891 non-null    bool
 13  Title_Dr        891 non-null    bool
 14  Title_Jonkheer  891 non-null    bool
 15  Title_Lady      891 non-null    bool
 16  Title_Major     891 non-null    bool
 17  Title_Master    891 non-null    bool
 18  Title_Miss      891 non-null    bool
 19  Title_Mr        891 non-null    bool
 20  Title_Mrs       891 non-null    bool
 21  Title_Rev       891 non-null    bool
 22  Title_Sir       891 non-null    bool
dtypes: bool(15), float64(2), int64(6)
memory usage: 68.9 KB

In [42]:
df.drop(columns=["PassengerId"],inplace=True)

In [43]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S,Title_Col,...,Title_Dr,Title_Jonkheer,Title_Lady,Title_Major,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rev,Title_Sir
0,0,3,1,22.0,1,0,7.2500,False,True,False,...,False,False,False,False,False,False,True,False,False,False
1,1,1,0,38.0,1,0,71.2833,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,1,3,0,26.0,0,0,7.9250,False,True,False,...,False,False,False,False,False,True,False,False,False,False
3,1,1,0,35.0,1,0,53.1000,False,True,False,...,False,False,False,False,False,False,False,True,False,False
4,0,3,1,35.0,0,0,8.0500,False,True,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.0,0,0,13.0000,False,True,False,...,False,False,False,False,False,False,False,False,True,False
887,1,1,0,19.0,0,0,30.0000,False,True,False,...,False,False,False,False,False,True,False,False,False,False
888,0,3,0,28.0,1,2,23.4500,False,True,False,...,False,False,False,False,False,True,False,False,False,False
889,1,1,1,26.0,0,0,30.0000,False,False,False,...,False,False,False,False,False,False,True,False,False,False
890,0,3,1,32.0,0,0,7.7500,True,False,False,...,False,False,False,False,False,False,True,False,False,False

In [47]:
# lets take the tabel the from the df
train =  df.drop("Survived",axis=1) # take the only feature 
label = df["Survived"]

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S,Title_Col,Title_Countess,...,Title_Dr,Title_Jonkheer,Title_Lady,Title_Major,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rev,Title_Sir
0,3,1,22.0,1,0,7.2500,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
1,1,0,38.0,1,0,71.2833,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,3,0,26.0,0,0,7.9250,False,True,False,False,...,False,False,False,False,False,True,False,False,False,False
3,1,0,35.0,1,0,53.1000,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
4,3,1,35.0,0,0,8.0500,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,1,27.0,0,0,13.0000,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
887,1,0,19.0,0,0,30.0000,False,True,False,False,...,False,False,False,False,False,True,False,False,False,False
888,3,0,28.0,1,2,23.4500,False,True,False,False,...,False,False,False,False,False,True,False,False,False,False
889,1,1,26.0,0,0,30.0000,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
890,3,1,32.0,0,0,7.7500,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [52]:
# Split data
X_train, X_test, y_train, y_test = train_test_split(train, label, test_size=0.2, random_state=42)

In [55]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

In [57]:
# lets the create the model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [58]:
predict = model.predict(X_test)

In [59]:
predict

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1])

In [60]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: Survived, Length: 179, dtype: int64

In [62]:
# Results
# print("Accuracy:", accuracy_score(y_test, predict))
accuracy_percent = accuracy_score(y_test, predict) * 100
print(f"Accuracy: {accuracy_percent:.2f}%")

print("\nClassification Report:\n", classification_report(y_test, predict))

Accuracy: 83.24%

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.85      0.86       105
           1       0.79      0.81      0.80        74

    accuracy                           0.83       179
   macro avg       0.83      0.83      0.83       179
weighted avg       0.83      0.83      0.83       179

In [63]:
# df.to_csv("model.csv",index=False)